### ISSUE TITLE
VkXcbSurfaceCreateInfoKHR's connection is not nint - Please replace with void*!

### ISSUE THREAD

**Issue by DeafMan1983** [terrafx/terrafx.interop.vulkan#59]
#### Description (optional)
Found in VkXcbSurfaceCreateInfoKHR's connection was `nint` But I find funny because I use this
```
xcb_connection_t* c;
xcb_window_t win;
...
VkXcbSurfaceCreateInfoKHR surf_info = new VkXcbSurfaceCreateInfoKHR
{
    connection = c, // <- Error wrong type nint
    window = win // <- correct type as uint
};
...
```

This section should contain an expanded description of the bug, if the title is
not sufficient.
Please replace with `nint` to `void*`!

#### Reproduction Steps

This section should contain an ordered list of steps that can be used to
reproduce the bug. Ideally, you would include as much information about your
environment as possible to help use in determining the best fix for the issue.

#### Expected Behavior

This section should contain a description of the behavior that is expected.

#### Actual Behavior

This section should contain a description of the actual behavior being observed.

**Comment by DeafMan1983** [comment]
Oh thank you! I can't wait for new feature `InlineArray`.

**Comment by tannergooding** [comment]
Resolved with https://github.com/terrafx/terrafx.interop.vulkan/pull/60
