### ISSUE TITLE
VkImageBlit2 Offsets are wrong types

### ISSUE THREAD

**Issue by TareHimself** [terrafx/terrafx.interop.vulkan#63]
#### Description (optional)

```c#
public unsafe partial struct VkImageBlit2
{
    public VkStructureType sType;

    [NativeTypeName("const void *")]
    public void* pNext;

    public VkImageSubresourceLayers srcSubresource;

    [NativeTypeName("VkOffset3D[2]")]
    public _srcOffsets_e__FixedBuffer srcOffsets;

    public VkImageSubresourceLayers dstSubresource;

    [NativeTypeName("VkOffset3D[2]")]
    public _dstOffsets_e__FixedBuffer dstOffsets;

    [InlineArray(2)]
    public partial struct _srcOffsets_e__FixedBuffer
    {
        public VkOffset3D e0;
    }

    [InlineArray(2)]
    public partial struct _dstOffsets_e__FixedBuffer
    {
        public VkOffset3D e0;
    }
}
```

Above srcOffsets and dstOffsets are meant to be arrays with two vk offsets each

**Comment by tannergooding** [comment]
The definition directly from `vulkan_core.h` is as below, which is exactly what is defined in C# here.
```cpp
typedef struct VkImageBlit2 {
    VkStructureType             sType;
    const void*                 pNext;
    VkImageSubresourceLayers    srcSubresource;
    VkOffset3D                  srcOffsets[2];
    VkImageSubresourceLayers    dstSubresource;
    VkOffset3D                  dstOffsets[2];
} VkImageBlit2;
```

The general syntax of `VkOffset3D srcOffsets[2];` defines a `constant array of 2 VkOffset3D`. When declared in a struct like this, the fields appear "inline" to the definition.

In .NET, the equivalent functionality is supported via a struct containing 1 field that is marked with the `[InlineArray(#)]` attribute. It is a new runtime feature with special language support that shipped in .NET 8/C# 12.

Given this, you can then do all the same operations as you would have access to in C. For example, given a `VkImageBlit2 vkImageBlit;` you can do `vkImageBlit.srcOffsets[1].y = 5;`

**Comment by tannergooding** [comment]
That is to say, there is no bug here and the definition is correct as is. You will find that the struct size and layout is identical to that defined in C. The general syntax used for accessing the members should be generally identical to the syntax used in C as well.

I expect this was filed due to an unfamiliarity with the new `InlineArray` feature found in .NET 8/C# 12.

**Comment by TareHimself** [comment]
My bad, Thanks.
